# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/cheatsheet_mission.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cs_mission_form(object):
    def setupUi(self, cs_mission_form):
        cs_mission_form.setObjectName("cs_mission_form")
        cs_mission_form.resize(501, 652)
        self.cheatsheet_mission = QtWidgets.QTextBrowser(cs_mission_form)
        self.cheatsheet_mission.setGeometry(QtCore.QRect(50, 30, 411, 551))
        self.cheatsheet_mission.setObjectName("cheatsheet_mission")

        self.retranslateUi(cs_mission_form)
        QtCore.QMetaObject.connectSlotsByName(cs_mission_form)

    def retranslateUi(self, cs_mission_form):
        _translate = QtCore.QCoreApplication.translate
        cs_mission_form.setWindowTitle(_translate("cs_mission_form", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cs_mission_form = QtWidgets.QWidget()
    ui = Ui_cs_mission_form()
    ui.setupUi(cs_mission_form)
    cs_mission_form.show()
    sys.exit(app.exec_())
