# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/example.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_expForm(object):
    def setupUi(self, expForm):
        expForm.setObjectName("expForm")
        expForm.resize(405, 327)
        self.groupBox_3 = QtWidgets.QGroupBox(expForm)
        self.groupBox_3.setGeometry(QtCore.QRect(30, 20, 161, 201))
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(10, 30, 138, 161))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.nakuja_n3_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.nakuja_n3_button.setObjectName("nakuja_n3_button")
        self.verticalLayout_5.addWidget(self.nakuja_n3_button)
        self.usc_traveler4_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.usc_traveler4_button.setObjectName("usc_traveler4_button")
        self.verticalLayout_5.addWidget(self.usc_traveler4_button)
        self.jaxa_ss520_button = QtWidgets.QPushButton(self.verticalLayoutWidget_5)
        self.jaxa_ss520_button.setObjectName("jaxa_ss520_button")
        self.verticalLayout_5.addWidget(self.jaxa_ss520_button)
        self.groupBox_4 = QtWidgets.QGroupBox(expForm)
        self.groupBox_4.setGeometry(QtCore.QRect(210, 20, 171, 201))
        self.groupBox_4.setObjectName("groupBox_4")
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox_4)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(10, 30, 148, 161))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.nakuja_liquid1_button = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.nakuja_liquid1_button.setObjectName("nakuja_liquid1_button")
        self.verticalLayout_6.addWidget(self.nakuja_liquid1_button)
        self.jaxa_h3_button = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.jaxa_h3_button.setObjectName("jaxa_h3_button")
        self.verticalLayout_6.addWidget(self.jaxa_h3_button)
        self.spacex_falcon9_button = QtWidgets.QPushButton(self.verticalLayoutWidget_6)
        self.spacex_falcon9_button.setObjectName("spacex_falcon9_button")
        self.verticalLayout_6.addWidget(self.spacex_falcon9_button)

        self.retranslateUi(expForm)
        QtCore.QMetaObject.connectSlotsByName(expForm)

    def retranslateUi(self, expForm):
        _translate = QtCore.QCoreApplication.translate
        expForm.setWindowTitle(_translate("expForm", "Examples"))
        self.groupBox_3.setTitle(_translate("expForm", "Solid propellant rocket"))
        self.nakuja_n3_button.setText(_translate("expForm", "Nakuja N3"))
        self.usc_traveler4_button.setText(_translate("expForm", "USC Traveler IV"))
        self.jaxa_ss520_button.setText(_translate("expForm", "JAXA SS-520"))
        self.groupBox_4.setTitle(_translate("expForm", "Liquid propellant rocket"))
        self.nakuja_liquid1_button.setText(_translate("expForm", "Nakuja Liquid-1"))
        self.jaxa_h3_button.setText(_translate("expForm", "JAXA H3"))
        self.spacex_falcon9_button.setText(_translate("expForm", "Space X Falcon 9"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    expForm = QtWidgets.QWidget()
    ui = Ui_expForm()
    ui.setupUi(expForm)
    expForm.show()
    sys.exit(app.exec_())
